# Generated by Django 5.2.5 on 2025-08-24 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0003_article_revision"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "data series",
            },
        ),
        migrations.CreateModel(
            name="DataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50)),
                ("value", models.DecimalField(decimal_places=4, max_digits=20)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="wiki.dataseries",
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
                "unique_together": {("series", "key")},
            },
        ),
    ]
