# Generated by Django 5.2.5 on 2025-08-25 00:00

from django.db import migrations, models


def populate_categories(apps, schema_editor):
    DataSeries = apps.get_model("wiki", "DataSeries")

    def parse(slug: str):
        parts = slug.split("/")
        category = parts[0] if len(parts) > 0 else ""
        sub = parts[1] if len(parts) > 1 else ""
        return category, sub

    for series in DataSeries.objects.all():
        if series.category and series.sub_category:
            continue
        category, sub = parse(series.slug)
        update_fields = []
        if not series.category:
            series.category = category
            update_fields.append("category")
        if not series.sub_category:
            series.sub_category = sub
            update_fields.append("sub_category")
        if update_fields:
            series.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0004_dataseries_datapoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataseries",
            name="category",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="dataseries",
            name="sub_category",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.RunPython(
            populate_categories, reverse_code=migrations.RunPython.noop
        ),
    ]
