# Generated by Django 5.2.5 on 2025-08-26

from django.db import migrations, models


def migrate_categories(apps, schema_editor):
    DataSeries = apps.get_model("wiki", "DataSeries")
    DataCategory = apps.get_model("wiki", "DataCategory")

    for series in DataSeries.objects.all():
        cats = []
        category = getattr(series, "category", None)
        sub = getattr(series, "sub_category", None)
        if category:
            cat, _ = DataCategory.objects.get_or_create(slug=category)
            cats.append(cat)
        if sub:
            cat, _ = DataCategory.objects.get_or_create(slug=sub)
            cats.append(cat)
        if cats:
            series.categories.add(*cats)


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0005_dataseries_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="dataseries",
            name="categories",
            field=models.ManyToManyField(blank=True, related_name="series", to="wiki.datacategory"),
        ),
        migrations.RunPython(migrate_categories, migrations.RunPython.noop),
        migrations.RemoveField(model_name="dataseries", name="category"),
        migrations.RemoveField(model_name="dataseries", name="sub_category"),
    ]
