[tool.ruff]
target-version = "py312"
line-length = 100
fix = true
unsafe-fixes = false

# pravidla patří nově sem:
[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]   # styl + chyby + isort + pyupgrade + bugbear
ignore = ["E501"]                     # délku řádků řeší Black, E501 vypínáme

[tool.ruff.lint.per-file-ignores]
"msa/tests/**/*.py" = ["F401", "F841", "E701", "E702", "B017"]
"fax_calendar/**/*.py" = ["B017"]     # test v kalendáři měl „blind exception“

[tool.black]
target-version = ["py312"]
line-length = 100
