# Generated by Django 5.2.5 on 2025-08-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="current_points",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="current_rank",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="player",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="player",
            name="nickname",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="player",
            name="rtf_current_points",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="RTF current points"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="rtf_current_rank",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="RTF current rank"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="turned_pro",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="country",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="handedness",
            field=models.CharField(
                blank=True,
                choices=[
                    ("right", "Right"),
                    ("left", "Left"),
                    ("ambi", "Ambidextrous"),
                    ("unknown", "Unknown"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="player",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
