# Generated by Django 5.2.5 on 2025-09-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="q_wc_slots",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="wc_slots",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournamententry",
            name="is_qwc",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="tournamententry",
            name="is_wc",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="tournamententry",
            name="promoted_by_qwc",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="tournamententry",
            name="promoted_by_wc",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
