# Generated by Django 5.2.6 on 2025-09-07 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msa", "0002_tournament_q_wc_slots_tournament_wc_slots_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="player1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matches_as_player1",
                to="msa.player",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="player2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matches_as_player2",
                to="msa.player",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="round",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["tournament", "round"], name="msa_match_tournam_fbf9b1_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["tournament", "position"], name="msa_match_tournam_625b18_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                fields=("tournament", "round", "position"),
                name="uniq_match_tournament_round_position",
            ),
        ),
    ]
