# Generated by Django 5.2.6 on 2025-09-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msa", "0003_match_player1_match_player2_match_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="draw_size",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
