# Generated by Django 5.2.5 on 2025-08-23 14:19

import fax_calendar.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msa", "0003_generate_player_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="birthdate",
            field=fax_calendar.fields.WoorldDateField(
                blank=True, max_length=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="turned_pro",
            field=fax_calendar.fields.WoorldDateField(
                blank=True, max_length=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="rankingsnapshot",
            name="as_of",
            field=fax_calendar.fields.WoorldDateField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="end_date",
            field=fax_calendar.fields.WoorldDateField(max_length=16),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="start_date",
            field=fax_calendar.fields.WoorldDateField(max_length=16),
        ),
    ]
