# Generated by Django 5.2.6 on 2025-09-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msa", "0004_tournament_draw_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="third_place_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
