# Generated by Django 5.2.5 on 2025-08-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msa", "0004_alter_player_birthdate_alter_player_turned_pro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
