# Generated by Django 5.2.5 on 2025-09-09 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msa", "0005_tournament_third_place_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryseason",
            name="draw_size",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(16, "16"), (32, "32"), (64, "64")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="tournamententry",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="msa.tournament",
            ),
        ),
    ]
