# Generated by Django 5.2.6 on 2025-09-09 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msa", "0006_alter_categoryseason_draw_size_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningUndoState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("day", models.DateField()),
                ("undo_stack", models.JSONField(default=list)),
                ("redo_stack", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="msa.tournament"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tournament", "day"), name="uniq_planning_undo_state"
                    )
                ],
            },
        ),
    ]
