# Generated by Django 5.2.5 on 2025-08-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msa", "0007_bracketpolicy_category_pointstable_prizetable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bracketpolicy",
            name="draw_size",
            field=models.IntegerField(default=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bracketpolicy",
            name="format",
            field=models.CharField(
                blank=True, choices=[("playoff", "Play-off")], max_length=50, null=True
            ),
        ),
    ]
