# Generated by Django 5.2.5 on 2025-08-30 07:39

import django.db.models.deletion
import fax_calendar.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msa", "0011_seedingpolicy_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventedition",
            name="best_of",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="eventedition",
            name="category_season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_editions",
                to="msa.categoryseason",
            ),
        ),
        migrations.AddField(
            model_name="eventedition",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="eventedition",
            name="end_date",
            field=fax_calendar.fields.WoorldDateField(
                blank=True, max_length=16, null=True
            ),
        ),
        migrations.AddField(
            model_name="eventedition",
            name="points_eligible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="eventedition",
            name="sanction_status",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="eventedition",
            name="scoring_rules",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="msa.scoringrule",
            ),
        ),
        migrations.AddField(
            model_name="eventedition",
            name="start_date",
            field=fax_calendar.fields.WoorldDateField(
                blank=True, max_length=16, null=True
            ),
        ),
        migrations.AddField(
            model_name="eventedition",
            name="venue",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
