# Generated by Django 5.2.6 on 2025-09-11 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msa", "0012_roundformat"),
    ]

    operations = [
        migrations.CreateModel(
            name="RankingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("ROLLING", "Rolling"), ("SEASON", "Season"), ("RTF", "Rtf")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("monday_date", models.DateField(db_index=True)),
                ("hash", models.CharField(db_index=True, max_length=64)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(default="auto", max_length=16)),
                ("is_alias", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="roundformat",
            name="uniq_round_format",
        ),
        migrations.AddField(
            model_name="tournament",
            name="seeding_monday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="roundformat",
            name="best_of",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(3, "3"), (5, "5")], default=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="roundformat",
            name="phase",
            field=models.CharField(
                blank=True,
                choices=[("QUAL", "Qualification"), ("MD", "Main Draw")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="roundformat",
            name="round_name",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="roundformat",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="round_formats",
                to="msa.tournament",
            ),
        ),
        migrations.AddConstraint(
            model_name="roundformat",
            constraint=models.UniqueConstraint(
                fields=("tournament", "phase", "round_name"), name="uniq_round_format_per_round"
            ),
        ),
        migrations.AddField(
            model_name="rankingsnapshot",
            name="alias_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aliases",
                to="msa.rankingsnapshot",
            ),
        ),
        migrations.AddIndex(
            model_name="rankingsnapshot",
            index=models.Index(fields=["type", "hash"], name="msa_ranking_type_ccb6e0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="rankingsnapshot",
            unique_together={("type", "monday_date")},
        ),
    ]
