# Generated by Django 5.2.5 on 2025-08-31 12:38

import django.db.models.deletion
import fax_calendar.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msa", "0012_eventedition_best_of_eventedition_category_season_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments",
                to="msa.season",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="season_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments",
                to="msa.categoryseason",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments",
                to="msa.category",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="end_date",
            field=fax_calendar.fields.WoorldDateField(
                blank=True, max_length=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="start_date",
            field=fax_calendar.fields.WoorldDateField(
                blank=True, max_length=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("upcoming", "Upcoming"),
                    ("ongoing", "Ongoing"),
                    ("finished", "Finished"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="venue",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
