# Generated by Django 5.2.6 on 2025-09-12 12:53

from django.db import migrations

import fax_calendar.fields


def _normalize_dates(apps, schema_editor):
    from fax_calendar.utils import parse_woorld_date, to_storage

    fields = [
        ("Season", "start_date"),
        ("Season", "end_date"),
        ("Tournament", "start_date"),
        ("Tournament", "end_date"),
        ("Tournament", "seeding_monday"),
        ("Schedule", "play_date"),
        ("RankingAdjustment", "start_monday"),
        ("RankingSnapshot", "monday_date"),
    ]
    for model_name, field_name in fields:
        Model = apps.get_model("msa", model_name)
        for obj in Model.objects.all():
            val = getattr(obj, field_name)
            if not val:
                continue
            if isinstance(val, str):
                try:
                    y, m, d = parse_woorld_date(val)
                    if None in (y, m, d):
                        continue
                    new_val = to_storage(y, m, d)
                except Exception:
                    continue
            else:
                new_val = val.strftime("%Y-%m-%d")
            if new_val != val:
                setattr(obj, field_name, new_val)
                obj.save(update_fields=[field_name])


class Migration(migrations.Migration):

    dependencies = [
        ("msa", "0013_ranking_snapshots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rankingadjustment",
            name="start_monday",
            field=fax_calendar.fields.WoorldDateField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="rankingsnapshot",
            name="monday_date",
            field=fax_calendar.fields.WoorldDateField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="play_date",
            field=fax_calendar.fields.WoorldDateField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="season",
            name="end_date",
            field=fax_calendar.fields.WoorldDateField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="season",
            name="start_date",
            field=fax_calendar.fields.WoorldDateField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="end_date",
            field=fax_calendar.fields.WoorldDateField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="seeding_monday",
            field=fax_calendar.fields.WoorldDateField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="start_date",
            field=fax_calendar.fields.WoorldDateField(blank=True, max_length=16, null=True),
        ),
        migrations.RunPython(_normalize_dates, migrations.RunPython.noop),
    ]
