# Generated by Django 5.2.5 on 2025-08-31 13:59

import django.db.models.deletion
import fax_calendar.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msa", "0013_tournament_season_tournament_season_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="allow_manual_bracket_edits",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="draw_policy",
            field=models.CharField(default="single_elim", max_length=20),
        ),
        migrations.AddField(
            model_name="tournament",
            name="draw_size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tournament",
            name="entry_deadline",
            field=fax_calendar.fields.WoorldDateField(
                blank=True, max_length=16, null=True
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="flex_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tournament",
            name="lucky_losers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tournament",
            name="qualifiers_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tournament",
            name="seeding_method",
            field=models.CharField(
                choices=[
                    ("ranking_snapshot", "Ranking snapshot"),
                    ("manual", "Manual"),
                    ("random", "Random"),
                    ("local_rating", "Local rating"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="seeding_rank_date",
            field=fax_calendar.fields.WoorldDateField(
                blank=True, max_length=16, null=True
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="seeds_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tournament",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("entry_open", "Entry Open"),
                    ("entry_locked", "Entry Locked"),
                    ("drawn", "Drawn"),
                    ("live", "Live"),
                    ("complete", "Complete"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TournamentEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("seed", models.IntegerField(blank=True, null=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("DA", "Direct Acceptance"),
                            ("Q", "Qualifier"),
                            ("WC", "Wildcard"),
                            ("LL", "Lucky Loser"),
                            ("ALT", "Alternate"),
                        ],
                        default="DA",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("withdrawn", "Withdrawn"),
                            ("replaced", "Replaced"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("position", models.IntegerField(blank=True, null=True)),
                ("seed_locked", models.BooleanField(default=False)),
                ("origin_note", models.CharField(blank=True, max_length=20)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "origin_match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origin_entries",
                        to="msa.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="msa.player"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="msa.tournament",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["seed", "player__name"],
                "unique_together": {("tournament", "player")},
            },
        ),
    ]
