# Generated by Django 5.2.5 on 2025-09-02 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msa", "0015_populate_tournament_entries"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="world_ranking_mode",
            field=models.CharField(
                choices=[
                    ("auto", "Auto"),
                    ("off", "Off"),
                    ("current", "Current"),
                    ("snapshot", "Snapshot"),
                ],
                default="auto",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="world_ranking_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments",
                to="msa.rankingsnapshot",
            ),
        ),
    ]
