# Generated by Django 5.2.5 on 2025-08-26 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Fighter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("nickname", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("stance", models.CharField(blank=True, max_length=50)),
                ("height_cm", models.PositiveIntegerField(blank=True, null=True)),
                ("reach_cm", models.PositiveIntegerField(blank=True, null=True)),
                ("birthdate", models.DateField(blank=True, null=True)),
            ],
            options={
                "indexes": [models.Index(fields=["slug"], name="mma_fighter_slug_05f6ee_idx")],
            },
        ),
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("content", models.TextField()),
                ("source_url", models.URLField(blank=True)),
                ("published_at", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    models.Index(fields=["slug"], name="mma_newsite_slug_550841_idx"),
                    models.Index(fields=["published_at"], name="mma_newsite_publish_84fb38_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("short_name", models.CharField(max_length=50)),
            ],
            options={
                "indexes": [models.Index(fields=["slug"], name="mma_organiz_slug_a59e69_idx")],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("date_start", models.DateTimeField()),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="mma.organization",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="mma.venue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeightClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=50)),
                ("limit_kg", models.PositiveIntegerField()),
            ],
            options={
                "indexes": [models.Index(fields=["slug"], name="mma_weightc_slug_7c046b_idx")],
            },
        ),
        migrations.CreateModel(
            name="Ranking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("date_effective", models.DateField()),
                (
                    "fighter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rankings",
                        to="mma.fighter",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rankings",
                        to="mma.organization",
                    ),
                ),
                (
                    "weight_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rankings",
                        to="mma.weightclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("red", "Red"),
                            ("blue", "Blue"),
                            ("draw", "Draw"),
                            ("nc", "No Contest"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("method", models.CharField(blank=True, max_length=100)),
                ("round", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("time", models.CharField(blank=True, max_length=10)),
                ("is_title_fight", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bouts",
                        to="mma.event",
                    ),
                ),
                (
                    "fighter_blue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bouts_as_blue",
                        to="mma.fighter",
                    ),
                ),
                (
                    "fighter_red",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bouts_as_red",
                        to="mma.fighter",
                    ),
                ),
                (
                    "weight_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bouts",
                        to="mma.weightclass",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["slug"], name="mma_event_slug_75fd61_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["date_start"], name="mma_event_date_st_048a97_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["organization"], name="mma_event_organiz_2dfb4d_idx"),
        ),
        migrations.AddIndex(
            model_name="ranking",
            index=models.Index(fields=["organization"], name="mma_ranking_organiz_9e62f0_idx"),
        ),
        migrations.AddIndex(
            model_name="ranking",
            index=models.Index(fields=["weight_class"], name="mma_ranking_weight__1ce72d_idx"),
        ),
        migrations.AddIndex(
            model_name="ranking",
            index=models.Index(fields=["date_effective"], name="mma_ranking_date_ef_1811ea_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="ranking",
            unique_together={("organization", "weight_class", "position", "date_effective")},
        ),
        migrations.AddIndex(
            model_name="bout",
            index=models.Index(fields=["event"], name="mma_bout_event_i_4a3430_idx"),
        ),
        migrations.AddIndex(
            model_name="bout",
            index=models.Index(fields=["weight_class"], name="mma_bout_weight__20e48e_idx"),
        ),
        migrations.AddIndex(
            model_name="bout",
            index=models.Index(fields=["fighter_red"], name="mma_bout_fighter_078ec8_idx"),
        ),
        migrations.AddIndex(
            model_name="bout",
            index=models.Index(fields=["fighter_blue"], name="mma_bout_fighter_ea47b9_idx"),
        ),
    ]
