from django.urls import reverse
from msa.models import Player


def test_slug_autogenerated(db):
    player = Player.objects.create(name="John Doe")
    assert player.slug == "john-doe"


def test_slug_collision(db):
    first = Player.objects.create(name="Same Name")
    second = Player.objects.create(name="Same Name")
    assert first.slug == "same-name"
    assert second.slug == "same-name-2"


def test_admin_changelist_columns(admin_client, db):
    Player.objects.create(name="Admin Player", handedness="right")
    url = reverse("admin:msa_player_changelist")
    resp = admin_client.get(url)
    assert resp.status_code == 200
    content = resp.content.decode()
    assert "Nickname" in content
    assert "Current rank" in content
    assert "RTF current rank" in content
    assert "By handedness" in content
